import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackButton from "./BackButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-5">
        <BackButton/>

          <>{children}</>
        </div>
      </body>
    </html>
  );
}
